### ISSUE TITLE
graph service time arguments 

### ISSUE THREAD

**Issue by emmdim** [guifi/snpservices#3]
Is the behaviour of the graph service in the  following lines correct?
https://github.com/emmdim/snpservices/blob/eb38fadafa064d1b5bd62ffc3d4b088d503834b9/services/graph.php#L105-L106

```
if ($end == 0)
        $start = -300;
```

This implies that if the argument $end is 0 no matter what is the argument $start, return a plot of the last half hour.
Is this the expected behaviour?

**Comment by rogerpueyo** [comment]
Yes, it is. However, the units are not minutes, but seconds. Therefore, if end is zero, you will miss the last 5 minutes (300 seconds) plot.

To sum up, if you don't specify neither start nor end, the default plot is [-24h, -5min], which is almost the last 24 hours [-24h, -0].
